
require("prototypes.capsules")
require("prototypes.recipes")
require("prototypes.technologies")
require("prototypes.enemies-base")
require("prototypes.enemies-space-age")
require("map-generation.resources-updates")
require("map-generation.bb")
require("map-generation.terrain")
require("map-generation.mirror")
require("map-generation.noise-visualization")
